fixtures:
  repositories:
    stdlib: 
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "3.2.0"
    logrotate:
      repo: "git://github.com/rodjek/puppet-logrotate.git"
      ref: "1.1.1"
  symlinks:
    graphite: "#{source_dir}"